const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function actual(file){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:()=>({}),JSON});return exports;}
const {orderSyncPayload}=actual('client-pos/src/utils/orderSyncPayload.ts'),{definiteFirstRejection}=actual('client-pos/src/utils/checkoutIntent.ts');
const request={storeId:'store',staffId:'staff',orderNumber:'OFFLINE-11111111-1111-4111-8111-111111111111',items:[{productId:'p',specId:'s',unitPrice:0}],pointsRedeemed:7,taxEnabled:false,note:'original'};
test('single/bulk payload is a deep copy of original snapshot, with no POS channel/default or display substitution',()=>{const row={storeId:'store',orderNumber:request.orderNumber,checkoutRequest:request,items:[{unitPrice:999}],channelId:'forged',pointsRedeemed:99};const payload=orderSyncPayload(row);assert.deepEqual(payload,request);payload.items[0].unitPrice=5;assert.equal(request.items[0].unitPrice,0);assert.equal(payload.channelId,undefined);});
test('legacy, mismatched store/identity and empty snapshots cannot be silently reconstructed',()=>{for(const change of [{checkoutRequest:undefined},{storeId:'foreign'},{orderNumber:'old-timestamp'},{checkoutRequest:{...request,items:[]}}])assert.throws(()=>orderSyncPayload({storeId:'store',orderNumber:request.orderNumber,checkoutRequest:request,...change}),/CHECKOUT_SNAPSHOT_REQUIRED/);});
test('only definite first-send refusals release intent; 5xx, conflicts and transport stay uncertain',()=>{for(const status of [400,401,403,404,422])assert.equal(definiteFirstRejection({response:{status}}),true);for(const message of ['OPEN_SHIFT_REQUIRED','SHIFT_DISABLED','PAYMENT_METHOD_DISABLED','PAYMENT_CONFIG_UNAVAILABLE'])assert.equal(definiteFirstRejection({response:{status:409,data:{message}}}),true);for(const e of [{code:'ERR_NETWORK'},{response:{status:500,data:{message:'Unique constraint'}}},{response:{status:503}},{response:{status:409,data:{message:'ORDER_IDEMPOTENCY_CONFLICT'}}}])assert.equal(definiteFirstRejection(e),false);});

test('inventory refusal releases only matching structured 409 rollback proof; text 500, missing proof and other identity stay unknown',()=>{const proof={response:{status:409,data:{message:'INVENTORY_INSUFFICIENT',rejection:{code:'INVENTORY_INSUFFICIENT',outcome:'not_committed',orderNumber:request.orderNumber}}}};assert.equal(definiteFirstRejection(proof,request.orderNumber),true);assert.equal(definiteFirstRejection(proof,'other'),false);assert.equal(definiteFirstRejection({response:{status:500,data:proof.response.data}},request.orderNumber),false);assert.equal(definiteFirstRejection({response:{status:409,data:{message:'INVENTORY_INSUFFICIENT'}}},request.orderNumber),false);});
