const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
test('downloaded updates never quit or install before legacy clearance', async () => {
  const handlers = {}, events = {}, sent = [];
  let quitCalls = 0;
  const autoUpdater = { setFeedURL() {}, on: (name, cb) => events[name] = cb, quitAndInstall() { quitCalls++; }, async downloadUpdate() {} };
  const api = {};
  const source = ts.transpileModule(fs.readFileSync('client-pos/electron/updater.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
  const versions = {};
  vm.runInNewContext(ts.transpileModule(fs.readFileSync('client-pos/src/utils/updateVersion.ts', 'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText, {exports:versions});
  vm.runInNewContext(source, { exports: api, require: name => name === 'electron-updater' ? { autoUpdater } : name === 'fs' ? fs : name.includes('updateVersion') ? versions : { ipcMain: { handle: (name, cb) => handlers[name] = cb }, shell:{showItemInFolder(){throw Error('No downloaded file expected')}}, app: { isPackaged: true, getVersion: () => '2026.10.309' } }, process, console: { log() {}, warn() {}, error() {} }, setInterval, setTimeout, clearInterval, clearTimeout });
  api.setupUpdater({ isDestroyed: () => false, webContents: { send: (...args) => sent.push(args) } });
  assert.equal(autoUpdater.autoInstallOnAppQuit, false);
  assert.equal(await handlers['download-update'](), true);
  events['update-downloaded']({ version: 'synthetic-next' });
  assert.equal(await handlers['install-update'](), false);
  assert.equal(quitCalls, 0);
  assert.equal((await handlers['show-update-installer']()).success, false);
  sent.length = 0;
  events['update-available']({version:'2026.10.309'});
  assert.equal(sent[0][1], 'up-to-date');
  events['update-available']({version:'2026.10.308'});
  assert.equal(sent[1][1], 'up-to-date');
  events['update-available']({version:'2026.10.310'});
  assert.equal(sent[2][1], 'available');
  assert.equal(quitCalls, 0);
});
