const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),ts=require('typescript');
const exportsObject={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('client-pos/electron/dataProfile.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,target:ts.ScriptTarget.ES2020}}).outputText,{exports:exportsObject,require});
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'pos-profile-owned-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const roaming=path.join(root,'roaming'),local=path.join(root,'local'),current=path.join(roaming,'bubble-tea-saas');return {root,roaming,local,current,resolve:()=>exportsObject.resolvePosDataProfile(current,roaming,local),data(folder){fs.mkdirSync(path.join(folder,'data'),{recursive:true});fs.writeFileSync(path.join(folder,'data/dev.db'),'owned bytes')}};}
test('existing default profile stays in place',t=>{const f=fixture(t);f.data(f.current);assert.equal(f.resolve(),f.current)});
test('legacy BTPS profile and original database bytes are reused',t=>{const f=fixture(t),old=path.join(f.roaming,'BTPS');f.data(old);assert.equal(f.resolve(),old);assert.equal(fs.readFileSync(path.join(old,'data/dev.db'),'utf8'),'owned bytes');assert.equal(fs.existsSync(f.current),false)});
test('legacy local-appdata profile is reused',t=>{const f=fixture(t),old=path.join(f.local,'BTPS');f.data(old);assert.equal(f.resolve(),old)});
test('pending IndexedDB alone is sufficient to preserve a historical profile',t=>{const f=fixture(t),old=path.join(f.roaming,'BTPS');fs.mkdirSync(path.join(old,'IndexedDB'),{recursive:true});assert.equal(f.resolve(),old);assert.equal(fs.existsSync(f.current),false)});
test('ambiguous historical profiles never select an empty default',t=>{const f=fixture(t);f.data(path.join(f.roaming,'BTPS'));f.data(path.join(f.local,'BTPS'));assert.throws(f.resolve,/AMBIGUOUS_POS_DATA_DIRECTORIES/);assert.equal(fs.existsSync(f.current),false)});
test('current and legacy data together require reconciliation instead of hiding either profile',t=>{const f=fixture(t);f.data(f.current);f.data(path.join(f.roaming,'BTPS'));assert.throws(f.resolve,/AMBIGUOUS_POS_DATA_DIRECTORIES/)});
test('verified upgrade marker reopens the 295 profile and leaves another database intact',t=>{const f=fixture(t),other=path.join(f.roaming,'BTPS');f.data(f.current);f.data(other);fs.writeFileSync(path.join(other,'upgrade-active-profile.json'),JSON.stringify({format:1,profile:f.current}));assert.equal(f.resolve(),f.current);assert.equal(fs.readFileSync(path.join(other,'data/dev.db'),'utf8'),'owned bytes')});
test('upgrade marker cannot point outside known POS profiles',t=>{const f=fixture(t),other=path.join(f.roaming,'BTPS');f.data(f.current);f.data(other);fs.writeFileSync(path.join(other,'upgrade-active-profile.json'),JSON.stringify({format:1,profile:f.root}));assert.throws(f.resolve,/AMBIGUOUS_POS_DATA_DIRECTORIES/)});
test('fresh installation uses its default without creating files during selection',t=>{const f=fixture(t);assert.equal(f.resolve(),f.current);assert.deepEqual(fs.readdirSync(f.root),[])});
