const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{module:m,exports:m.exports,require:n=>{if(n in imports)return imports[n];throw Error(n)},Date,Map,Set,console});return m.exports;}
const labels=load('shared/utils/expenseCategories.ts');
test('six defaults translate in all languages including historical raw keys',()=>{for(const lang of ['zh','en','id'])for(const key of ['rent','utilities','supplies','salary','reimbursement','other']){const name=labels.expenseCategoryName({key,label:''},lang);assert.ok(name.trim());assert.notEqual(name,key);assert.equal(labels.expenseCategoryName({key,label:key},lang),name)}assert.equal(labels.expenseCategoryName({key:'custom',label:'网费'},'id'),'网费');assert.equal(labels.expenseCategoryName({key:'custom',label:'网费',labelId:'Internet'},'id'),'Internet');});
test('legacy categories stay available unless explicitly hidden',()=>{assert.equal(labels.visibleInPos({key:'old'}),true);assert.equal(labels.visibleInPos({key:'hidden',posVisible:false}),false);assert.equal(labels.visibleInPos({key:'shown',posVisible:true}),true)});
const zod=require('../../server/node_modules/zod'),manual=load('server/src/services/ShiftManualReceipts.ts',{zod});
test('four whole nonnegative bounded amounts; zero explicit, missing not zero',()=>{assert.equal(manual.manualReceiptsSchema.safeParse({cash:0,qris:0,shopeefood:0,gofood:0}).success,true);for(const cash of [-1,1.5,NaN,Infinity,'100',2147483648])assert.equal(manual.manualReceiptsSchema.safeParse({cash,qris:0,shopeefood:0,gofood:0}).success,false);assert.equal(manual.manualReceiptsSchema.safeParse({cash:0,qris:0}).success,false)});
test('scoped closed shifts aggregate by close time without modifying order revenue; legacy reports remain null',async()=>{const amounts={cash:100000,qris:200000,shopeefood:300000,gofood:400000};let query;const start=new Date('2026-10-09T00:00:00+07:00'),end=new Date('2026-10-10T00:00:00+07:00');const db={shiftSession:{findMany:async q=>{assert.equal(q.where.storeId,'store');assert.equal(q.where.status,'closed');assert.equal(q.where.closedAt.gte,start);assert.equal(q.where.closedAt.lt,end);return [{id:'reported',shift:'day',closedAt:start},{id:'legacy',shift:'night',closedAt:start}]}},config:{findMany:async q=>{query=q;return [{key:'pos.shift.report:reported',value:JSON.stringify({manualReceipts:amounts})},{key:'pos.shift.report:legacy',value:'{"actualCash":0}'}]}}};const result=await manual.getHandoverReceipts(db,'store',start,end);assert.equal(query.where.storeId,'store');assert.equal(result.list[1].manualReceipts,null);assert.equal(result.totals.qris,200000);assert.equal(result.totals.gofood,400000);assert.equal(result.unreportedShifts,1);assert.equal(result.source,'manual_handover');assert.ok(!('revenue' in result));});
test('backend rejects hidden POS categories but allows exact replay after category hidden',async()=>{let creates=0,saved=null;const input={requestId:'123e4567-e89b-42d3-a456-426614174000',category:'rent',amount:100,quantity:1,description:'synthetic'};const tx={store:{update:async()=>{}},expense:{findFirst:async()=>saved,create:async()=>{creates++;return {id:'new'}}},financeAuditLog:{findFirst:async()=>({newValue:'{"quantity":1}'}),create:async()=>{}},config:{findUnique:async()=>({value:JSON.stringify([{key:'rent',posVisible:false}])})}};const svc=load('server/src/services/PosExpenseService.ts',{'../config/database':{__esModule:true,default:{$transaction:async f=>f(tx)}},crypto:require('node:crypto'),zod,'./ExpenseService':{normalizeExpenseDate:()=>new Date(),getExpenseCategories:async()=>[],withPurchaseQuantities:async a=>a}});await assert.rejects(()=>svc.createPosExpense({id:'u',storeId:'store'},input),/POS_EXPENSE_CATEGORY_INVALID/);assert.equal(creates,0);saved={id:'saved',category:'rent',amount:10000,description:'synthetic'};assert.equal((await svc.createPosExpense({id:'u',storeId:'store'},input)).id,'saved');assert.equal(creates,0)});
