// Actual online card checkout AST (cash/manual QRIS use the native offline suite); transactional IndexedDB behavior is covered by the real browser suite.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const source=fs.readFileSync('client-pos/src/pages/POSPage.tsx','utf8'),ast=ts.createSourceFile('POSPage.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let checkout,shiftGuard;
(function visit(n){if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='handleCheckout')checkout=n.initializer.getText(ast);if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='requireOpenShift')shiftGuard=n.initializer.getText(ast);ts.forEachChild(n,visit);})(ast);
const code=ts.transpileModule('globalThis.requireOpenShift='+shiftGuard+';globalThis.checkout='+checkout,{compilerOptions:{target:ts.ScriptTarget.ES2020}}).outputText;
function fixture(){const events=[],state={busy:false,failed:false,modal:true};const c={reportReceivedPayment:async()=>{},paymentIssue:null,appVersion:'2026.10.309',settledCartRef:{current:null},navigator:{onLine:true},useAuthStore:{getState:()=>({token:'synthetic-only'})},selectedCoupon:null,basketGeneration:'0',recovery:{blocked:false,confirmed:[]},cart:[{productId:'p',specId:'s',productName:'Tea',specName:'Regular',quantity:1,unitPrice:10000,addons:[]}],isCheckingOut:false,useOrderStore:{getState:()=>({isCheckingOut:state.busy})},paymentConfigReady:true,paymentMethods:[{id:'card'}],paymentMethod:'card',paidAmount:'20000',paymentSettings:{maxCashAmount:0},qrisData:{status:'idle'},selectedChannel:{id:'dine_in',code:'DINE_IN',nameKey:'pos.dineIn'},posChannels:[],dineInCount:1,customerCount:1,tableNumber:'7',platformOrderId:'',user:{storeId:'store',staff:{id:'staff'}},total:10000,subtotal:10000,tax:0,discountAmount:0,member:null,pointsToRedeem:0,taxSettings:{enabled:false},paymentModalOrderNum:'T001',appliedPromotion:null,isManualDiscount:false,orderNote:'original',hardwareSettings:{autoOpenCashDrawer:false},posReceipt:{autoPrint:false},soundSettings:{error:true},t:x=>x,formatCurrency:String,logPOSAction:()=>{},playSoundWithSettings:()=>{},showToast:(...args)=>events.push(['toast',...args]),setIsCheckingOut:v=>state.busy=v,setOfflineSaveFailed:v=>state.failed=v,prepareCheckout:async request=>{events.push(['prepare']);return {request:{...request,orderNumber:'OFFLINE-stable'}};},claimCheckout:async()=>events.push(['claim']),finishCheckout:async(_,outcome)=>{events.push(['finish',outcome]);c.recovery.blocked=outcome==='review';},definiteFirstRejection:e=>[400,401,403,409].includes(e.response?.status),posApi:{getCurrentShift:async()=>({data:{data:{hasOpenShift:true,shift:{id:'session',shift:'day'}}}}),createOrder:async request=>{events.push(['api',request]);throw {code:'ERR_NETWORK'};}},printReceipt:()=>events.push(['print']),printKitchenOrder:()=>events.push(['print']),printCupStickers:()=>events.push(['print']),electronAPI:{sendOrderComplete:()=>events.push(['display'])},clearCart:()=>{events.push(['clear']);c.cart=[];},setShowPaymentModal:v=>{state.modal=v;events.push(['modal',v]);}};vm.runInNewContext(code,c);return {c,events,state,run:()=>c.checkout()};}
const output=f=>f.events.filter(e=>['print','display','clear','modal'].includes(e[0]));
test('immutable identity persisted and claimed before POST; transport uncertainty never clears or prints',async()=>{const f=fixture();await f.run();assert.deepEqual(f.events.slice(0,3).map(e=>e[0]),['prepare','claim','api']);assert.equal(f.events[2][1].orderNumber,'OFFLINE-stable');assert.deepEqual(f.events.find(e=>e[0]==='finish'),['finish','review']);assert.equal(output(f).length,0);assert.equal(f.c.cart.length,1);assert.equal(f.state.busy,false);});
test('first local save failure blocks all HTTP and preserves payment/cart',async()=>{const f=fixture();f.c.prepareCheckout=async()=>{throw Error('quota');};await f.run();assert.equal(f.events.filter(e=>e[0]==='api').length,0);assert.equal(f.state.failed,true);assert.equal(output(f).length,0);assert.equal(f.c.cart.length,1);});
test('sent-state claim failure never sends prepared request',async()=>{const f=fixture();f.c.claimCheckout=async()=>{throw Error('claim quota');};await f.run();assert.equal(f.events.filter(e=>e[0]==='api').length,0);assert.equal(f.state.failed,true);assert.equal(output(f).length,0);});
test('same-render repeated clicks during prepare cause one request',async()=>{const f=fixture();let release;f.c.prepareCheckout=request=>new Promise(r=>release=()=>r({request:{...request,orderNumber:'OFFLINE-stable'}}));const first=f.run();await f.run();await new Promise(resolve=>setImmediate(resolve));release();await first;assert.equal(f.events.filter(e=>e[0]==='api').length,1);});
test('known HTTP refusal releases intent but preserves cart; 5xx/unique/local uncertainty retains it',async()=>{for(const status of [400,401,403,409,500,503,undefined]){const f=fixture();f.c.posApi.createOrder=async()=>{throw {response:status?{status}:undefined};};await f.run();assert.equal(f.events.find(e=>e[0]==='finish')[1],status&&status<500?'rejected':'review');assert.equal(output(f).length,0);assert.equal(f.c.cart.length,1);}});
test('durable acknowledgement failure after HTTP success is uncertainty with zero outputs',async()=>{const f=fixture();f.c.posApi.createOrder=async request=>({data:{data:{id:'order',orderNumber:request.orderNumber}}});f.c.finishCheckout=async(_,result)=>{f.events.push(['finish',result]);if(result==='accepted')throw Error('quota');};await f.run();assert.equal(output(f).length,0);assert.deepEqual(f.events.filter(e=>e[0]==='finish').map(e=>e[1]),['accepted','review']);assert.equal(f.c.cart.length,1);});
test('recovery barrier prevents later mutable cart from minting another identity',async()=>{const f=fixture();await f.run();f.c.cart.push({...f.c.cart[0],productId:'new'});await f.run();assert.equal(f.events.filter(e=>e[0]==='prepare').length,1);assert.equal(f.events.filter(e=>e[0]==='api').length,1);assert.equal(f.c.cart.length,2);});
test('configuration failure/all-off/disabled choice preserves cart before any journal or API',async()=>{for(const setup of [c=>c.paymentIssue='configuration',c=>c.paymentIssue='method']){const f=fixture();setup(f.c);await f.run();assert.equal(f.events.some(e=>['prepare','api'].includes(e[0])),false);assert.equal(f.c.cart.length,1);}});

test('confirmed order followed by local output error clears original sale and never allows another send',async()=>{const f=fixture();f.c.posApi.createOrder=async request=>{f.events.push(['api',request]);return {data:{data:{id:'order',orderNumber:request.orderNumber}}};};await f.run();assert.equal(f.events.find(e=>e[0]==='finish')[1],'accepted');assert.equal(f.c.cart.length,0);assert.equal(f.state.modal,false);await f.run();assert.equal(f.events.filter(e=>e[0]==='api').length,1);});

test('stale basket generation refusal before first send clears obsolete basket and never sends or prints',async()=>{const f=fixture();f.c.prepareCheckout=async()=>{throw Error('CHECKOUT_BASKET_STALE');};await f.run();assert.equal(f.events.some(e=>e[0]==='api'),false);assert.equal(f.c.cart.length,0);assert.equal(f.state.modal,false);assert.equal(f.events.some(e=>['print','display'].includes(e[0])),false);assert.equal(f.events.find(e=>e[0]==='toast')[1],'checkoutIntent.staleBasket');});
