const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function actual(row=null){const m={exports:{}};let query;vm.runInNewContext(ts.transpileModule(fs.readFileSync('server/src/services/OrderReplayService.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,{module:m,exports:m.exports,require:name=>name==='crypto'?require('node:crypto'):{__esModule:true,default:{order:{findUnique:async q=>{query=q;return row;}}}},Date});return {...m.exports,query:()=>query};}
const request={storeId:'store',staffId:'staff',orderNumber:'OFFLINE-11111111-1111-4111-8111-111111111111',paymentMethod:'cash',items:[{productId:'p',productName:'Tea',specId:'s',specName:'Regular',quantity:1,unitPrice:10000}]};
const response={id:'order',orderNumber:request.orderNumber,totalAmount:10000,ppnAmount:0,grandTotal:9999,status:'completed',paymentMethod:'cash',items:[],createdAt:new Date('2026-10-07T00:00:00Z')};
function stored(){const a=actual();return {id:response.id,storeId:request.storeId,orderNumber:request.orderNumber,requestFingerprint:a.orderRequestFingerprint(request),requestReceipt:a.encodeOrderReceipt(request,response)};}
test('fingerprint is stable under object-key order and omitted protocol defaults',()=>{const a=actual();assert.equal(a.orderRequestFingerprint(request),a.orderRequestFingerprint({...request,status:'completed',taxEnabled:true,customerCount:1,discountAmount:0,pointsRedeemed:0,items:[{unitPrice:10000,quantity:1,specName:'Regular',specId:'s',productName:'Tea',productId:'p',addons:[]}]}));});
test('request identity, actor, financial input, shift, catalog quote and contextual content change fingerprint',()=>{const a=actual(),hash=a.orderRequestFingerprint(request);for(const change of [{storeId:'other'},{staffId:'other'},{orderNumber:'another'},{pointsRedeemed:1},{discountAmount:1},{taxEnabled:false},{paymentMethod:'qris'},{customerCount:2},{status:'suspended'},{memberId:'m'},{channelId:'c'},{pickupNumber:'A01'},{note:'changed'},{shiftSessionId:'session'},{items:[{...request.items[0],unitPrice:9999}]},{items:[{...request.items[0],addons:[{name:'Pearl',price:0}]}]}])assert.notEqual(a.orderRequestFingerprint({...request,...change}),hash);});
test('server receipt is versioned, excludes internal fields and returns original authoritative amounts',async()=>{const row=stored(),a=actual(row);const result=await a.findOrderReplay(request);assert.equal(result.grandTotal,9999);assert.equal(result.createdAt.toISOString(),response.createdAt.toISOString());assert.equal(result.requestReceipt,undefined);assert.equal(JSON.parse(row.requestReceipt).version,1);});
test('same identity different content conflicts, without certifying an old sale',async()=>{await assert.rejects(actual(stored()).findOrderReplay({...request,discountAmount:1}),e=>e.code==='ORDER_IDEMPOTENCY_CONFLICT');});
test('legacy NULL identity and malformed/version/foreign response receipts fail closed',async()=>{for(const change of [{requestFingerprint:null},{requestReceipt:null},{requestReceipt:'broken'},{requestReceipt:JSON.stringify({...JSON.parse(stored().requestReceipt),version:2})},{requestReceipt:JSON.stringify({...JSON.parse(stored().requestReceipt),response:{...response,id:'foreign'}})}])await assert.rejects(actual({...stored(),...change}).findOrderReplay(request),e=>e.code==='ORDER_REPLAY_UNVERIFIED');});
test('foreign-store identity cannot return its receipt; generated short pickup is not a replay key',async()=>{await assert.rejects(actual({...stored(),storeId:'foreign'}).findOrderReplay(request),e=>e.code==='ORDER_STORE_MISMATCH');const a=actual(stored());assert.equal(await a.findOrderReplay({...request,orderNumber:'A01'}),null);assert.equal(a.query(),undefined);});
test('normal order projection preserves history values and hides both nullable metadata fields',()=>{const input={id:'legacy',finalAmount:50,requestFingerprint:null,requestReceipt:null},result=actual().publicOrder(input);assert.equal(result.finalAmount,50);assert.equal('requestReceipt'in result,false);assert.equal('requestFingerprint'in result,false);assert.equal(input.requestReceipt,null);});
