const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{module:m,exports:m.exports,require:n=>{if(n in imports)return imports[n];throw Error(n)},Date,Set,console});return m.exports;}
const {cartAuditSnapshot}=load('client-pos/src/utils/cartAudit.ts'),projection=load('server/src/utils/posCartState.ts');const log=(action,metadata={})=>({action,metadata:JSON.stringify(metadata),createdAt:new Date(),entityId:'item'});
const tea={id:'tea-large',productId:'tea',productName:'Milk tea',specName:'Large',quantity:2,unitPrice:10000,addons:[{name:'Pearls',price:2000,qty:2}]};
test('current snapshot includes variant, quantities, paid add-ons and summed merchandise value',()=>{const snapshot=cartAuditSnapshot([tea,{...tea,id:'coffee',productName:'Coffee',quantity:1,unitPrice:15000,addons:[]}]);const result=projection.projectCartState([log('cart_update',{cartSnapshot:snapshot})]);assert.equal(result.itemCount,3);assert.equal(result.subtotal,43000);assert.equal(result.items[0].productName,'Milk tea');assert.equal(result.items[0].specName,'Large');assert.equal(result.items[0].unitPrice,14000);assert.equal(result.items[0].lineTotal,28000);assert.equal(result.items[0].addons[0].quantity,2);assert.equal(result.detailSource,'snapshot');});
test('quantity changes, item removal and empty carts replace earlier contents instead of counting add events',()=>{const states=[log('cart_add',{productName:'Milk tea',quantity:5,unitPrice:10000}),log('cart_update',{cartSnapshot:cartAuditSnapshot([tea])}),log('cart_update',{cartSnapshot:cartAuditSnapshot([{...tea,quantity:1,addons:[]}])})];assert.equal(projection.projectCartState(states).itemCount,1);assert.equal(projection.projectCartState(states).subtotal,10000);assert.equal(projection.projectCartState([...states,log('cart_update',{cartSnapshot:cartAuditSnapshot([])})]).itemCount,0);});
test('completion and clearing end a cart, while a later cart in the same session is visible',()=>{const added=log('cart_add',{productName:'Tea',quantity:2,unitPrice:10000});for(const action of ['checkout_complete','cart_clear','suspend']){assert.equal(projection.projectCartState([added,log(action)]).itemCount,0);assert.equal(projection.projectCartState([added,log(action),added]).itemCount,2);}});
test('old records retain names and known base prices; missing add-on prices never fabricate a grand total',()=>{const old=log('cart_add',{productName:'Tea',specName:'Large',quantity:2,unitPrice:10000,addons:['Pearls']});const result=projection.projectCartState([old]);assert.equal(result.items[0].productName,'Tea');assert.equal(result.items[0].lineTotal,20000);assert.equal(result.subtotal,null);assert.equal(result.detailSource,'legacy');assert.equal(projection.projectCartState([log('cart_add',{productName:'Tea',quantity:2,unitPrice:10000,addons:[]})]).subtotal,20000);});
test('malformed snapshots and unrecorded old mutations do not certify stale names or amounts',()=>{const added=log('cart_add',{productName:'Tea',quantity:2,unitPrice:10000});const malformed=cartAuditSnapshot([tea]);malformed.subtotal=1;for(const last of [log('cart_update',{cartSnapshot:malformed}),log('resume',{itemCount:2})]){const result=projection.projectCartState([added,last]);assert.equal(result.itemCount,2);assert.equal(result.items.length,0);assert.equal(result.subtotal,null);assert.equal(result.detailSource,'unavailable');}});
test('session reads are scoped to store AND staff, deduplicate renamed staff, and do not suppress new carts after an earlier sale',async()=>{let queries=[];const db={pOSActionLog:{groupBy:async q=>{assert.equal(q.where.storeId,'owned');return [{sessionId:'same',staffId:'a',staffName:'Old'},{sessionId:'same',staffId:'a',staffName:'New'},{sessionId:'same',staffId:'b',staffName:'B'}]},findMany:async q=>{queries.push(q);assert.equal(q.where.storeId,'owned');assert.equal(q.where.sessionId,'same');assert.ok(['a','b'].includes(q.where.staffId));return [log('checkout_complete'),{...log('cart_update',{cartSnapshot:cartAuditSnapshot([{...tea,quantity:q.where.staffId==='a'?1:2}])}),staffName:q.where.staffId}]}}};const service=load('server/src/services/POSActionLogService.ts',{'../config/database':{__esModule:true,default:db},'../socket':{socketManager:{}},'../utils/posCartState':projection});const sessions=await service.getActiveSessions('owned');assert.equal(queries.length,2);assert.equal(sessions.length,2);assert.equal(sessions[0].itemCount,1);assert.equal(sessions[1].itemCount,2);assert.equal(sessions[0].staffName,'a');});

test('failure explanations distinguish inventory, uncertain network outcomes and unrecognized errors',()=>{const {readPOSFailure}=load('client-admin/src/utils/posMonitorFailure.ts');assert.equal(readPOSFailure(JSON.stringify({failureCode:'INVENTORY_INSUFFICIENT',httpStatus:409,outcome:'rejected'})).reasonKey,'failureStock');const network=readPOSFailure({failureCode:'ERR_NETWORK',outcome:'review'});assert.equal(network.reasonKey,'failureNetwork');assert.equal(network.needsReview,true);assert.equal(readPOSFailure({failureCode:'UNRECOGNIZED'}).reasonKey,'failureUnknown');assert.equal(readPOSFailure(null).reasonKey,'failureNotRecorded');assert.equal(readPOSFailure('broken').code,'');});
