const test=process.env.RECEIPT_NATIVE_ONLY ? ()=>{} : require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),http=require('node:http'),path=require('node:path'),ts=require('typescript');
const source=fs.readFileSync('client-pos/electron/main.ts','utf8'),tree=ts.createSourceFile('main.ts',source,ts.ScriptTarget.Latest,true);
const names=['loadLogoBuffer','imageBufferToEscPosRaster','buildReceiptEscPosBuffer','generateReceiptText','getVisualWidth','padEndVisual','padStartVisual','centerText','repeatChar','truncate','formatRp','formatDateTime','buildEscPosBarcode','buildEscPosQRCode'];
const functions=tree.statements.filter(n=>ts.isFunctionDeclaration(n)&&names.includes(n.name?.text)).map(n=>n.getText(tree)).join('\n');
const moduleSource=ts.transpileModule(fs.readFileSync('client-pos/electron/receiptLogo.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;
const exportsObject={};vm.runInNewContext(moduleSource,{exports:exportsObject,require,Buffer,URL,setTimeout,clearTimeout});
const fixturePng=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0]);
function renderer(imageApi){
 const context={Buffer,Math,Date,Set,URL,fs,path,require,setTimeout,clearTimeout,fetchReceiptLogo:exportsObject.fetchReceiptLogo,logoMemoryCache:new Map(),writeCrash:()=>{},getResourcePath:()=>'/tmp/receipt-nonexistent',app:{getAppPath:()=>'/tmp/receipt-nonexistent'},encodeEscPosText:s=>Buffer.from(s,'utf8'),nativeImage:imageApi||{createFromBuffer:()=>({isEmpty:()=>false,getSize:()=>({width:8,height:8}),resize:({width,height})=>({toBitmap:()=>Buffer.alloc(width*height*4,0xff)})})}};
 vm.runInNewContext(ts.transpileModule(functions+'\nglobalThis.render=buildReceiptEscPosBuffer;globalThis.load=loadLogoBuffer;',{compilerOptions:{target:ts.ScriptTarget.ES2020}}).outputText,context);return context;
}
function block(type,config={},style={},order=0,enabled=true){return {type,config,style,order,enabled};}
async function server(fn){const s=http.createServer(fn);await new Promise(r=>s.listen(0,'127.0.0.1',r));return {url:'http://127.0.0.1:'+s.address().port,close:()=>new Promise(r=>{s.closeAllConnections();s.close(r)})};}
test('first receipt waits for remote logo and respects template override, alignment, disabled header and blocks',async()=>{
 const hits=[];const s=await server((req,res)=>{hits.push(req.url);setTimeout(()=>{res.writeHead(200,{'Content-Type':'image/png'});res.end(fixturePng)},40)});
 try{const ctx=renderer(),data={paperSize:'58mm',storeLogo:'data:image/png;base64,'+fixturePng.toString('base64'),storeName:'SHOULD_NOT_PRINT',showLogo:true,printWarnings:[],blocks:[block('header',{text:'HIDDEN'},{},0,false),block('logo',{url:s.url+'/override',width:120},{align:'right'},1),block('customText',{text:'Custom footer'},{bold:false,fontSize:'small',align:'left'},2)]};const bytes=await ctx.render(data);assert.deepEqual(hits,['/override']);assert.ok(bytes.includes(Buffer.from([0x1b,0x61,2,0x1d,0x76,0x30,0])),'actual logo raster, aligned right');assert.ok(bytes.includes(Buffer.from('Custom footer')));assert.ok(!bytes.includes(Buffer.from('SHOULD_NOT_PRINT')));assert.ok(!bytes.includes(Buffer.from('HIDDEN')));assert.equal(data.printWarnings.length,0);await ctx.render(data);assert.equal(hits.length,1,'same logo cached');}finally{await s.close()}
});
test('unavailable logo produces visible warning and never reintroduces a disabled header',async()=>{
 const s=await server((_req,res)=>{res.writeHead(404);res.end('missing')});try{const ctx=renderer(),data={storeName:'HIDDEN_STORE',showLogo:true,printWarnings:[],blocks:[block('logo',{url:s.url+'/missing'}),block('header',{text:'HIDDEN_HEADER'},{},1,false),block('customText',{text:'Visible'}, {},2)]};const bytes=await ctx.render(data);assert.equal(data.printWarnings[0],'LOGO_UNAVAILABLE');assert.ok(bytes.includes(Buffer.from('Visible')));assert.ok(!bytes.includes(Buffer.from('HIDDEN_STORE')));assert.ok(!bytes.includes(Buffer.from('HIDDEN_HEADER')));assert.ok(!bytes.includes(Buffer.from([0x1d,0x76,0x30,0])));}finally{await s.close()}
});
test('logo download follows redirects and rejects large, stalled and non-HTTP responses within one deadline',async()=>{
 const s=await server((req,res)=>{if(req.url==='/redirect'){res.writeHead(302,{Location:'/png'});res.end()}else if(req.url==='/png')res.end(fixturePng);else if(req.url==='/bad-redirect'){res.writeHead(302,{Location:'http://['});res.end()}else if(req.url==='/large'){res.writeHead(200,{'Content-Length':'100'});res.end(Buffer.alloc(100))}});try{assert.deepEqual(await exportsObject.fetchReceiptLogo(s.url+'/redirect',500),fixturePng);assert.equal(await exportsObject.fetchReceiptLogo(s.url+'/large',500,10),null);assert.equal(await exportsObject.fetchReceiptLogo(s.url+'/bad-redirect',500),null);const start=Date.now();assert.equal(await exportsObject.fetchReceiptLogo(s.url+'/stalled',80),null);assert.ok(Date.now()-start<500);assert.equal(await exportsObject.fetchReceiptLogo('file:///tmp/image',80),null);}finally{await s.close()}
});
test('template style controls pickup number and narrow large total without forcing a large bold queue heading',async()=>{
 const ctx=renderer(),data={paperSize:'58mm',language:'en',pickupNumber:'A01',orderNum:'ORDER-HIDDEN',total:1000000,blocks:[block('orderInfo',{showOrderNo:false,showDate:false,showTime:false},{bold:false,fontSize:'normal',align:'left'}),block('total',{totalLabel:'Grand total'},{bold:false,fontSize:'large',align:'right'},1)]};const bytes=await ctx.render(data);const pickup=bytes.indexOf(Buffer.from('A01')),total=bytes.indexOf(Buffer.from('Grand total'));assert.ok(pickup>=0&&total>pickup);assert.ok(!bytes.subarray(0,total).includes(Buffer.from([0x1b,0x45,1])),'no forced bold');assert.ok(!bytes.subarray(0,pickup).includes(Buffer.from([0x1d,0x21,0x11])),'queue follows normal template size');assert.ok(bytes.subarray(pickup,total).includes(Buffer.from([0x1d,0x21,0x11])),'large total stays large');assert.ok(!bytes.includes(Buffer.from('ORDER-HIDDEN')));
});
test('empty explicit template never prints the hardcoded legacy receipt',async()=>{const bytes=await renderer().render({blocks:[],storeName:'NO LEGACY',total:16000});assert.ok(!bytes.includes(Buffer.from('NO LEGACY')));assert.equal(bytes.toString(),'\n\n');});
test('date and time use separate template rows and item alignment honors its style',async()=>{const ctx=renderer(),bytes=await ctx.render({language:'en',orderDate:'2026-10-07T11:00:00Z',items:[{productName:'Tea',quantity:1,unitPrice:10000}],blocks:[block('orderInfo',{showOrderNo:false,showDate:true,showTime:true},{bold:false}),block('items',{showHeader:false},{align:'right',bold:false},1)]});assert.ok(bytes.includes(Buffer.from('Date')));assert.ok(bytes.includes(Buffer.from('Time')));const item=bytes.indexOf(Buffer.from('Tea'));assert.ok(item>0);assert.ok(bytes.subarray(0,item).includes(Buffer.from([0x1b,0x61,2])));});
module.exports={renderer,fixturePng,block};
