import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { activitiesApi } from '../services/api'
import { activityLabel, languageIndex } from '../../../shared/utils/activityLabels'
import { activityState } from '../../../shared/utils/activities'
export function ActivityPanel({activities,quote,giftSelections,onGiftChange,memberId,groupId,onGroupChange}:{activities:any[];quote:any;giftSelections:Record<string,string>;onGiftChange:(value:Record<string,string>)=>void;memberId?:string;groupId:string;onGroupChange:(id:string)=>void}){
 const {i18n}=useTranslation(),lang=languageIndex(i18n.language),l=(zh:string,en:string,id:string)=>[zh,en,id][lang]
 const [inviterCode,setInviterCode]=useState('')
 const [open,setOpen]=useState(false),[groups,setGroups]=useState<any[]>([]),[grants,setGrants]=useState<any[]>([]),[error,setError]=useState('')
 const refresh=()=>Promise.all([activitiesApi.groups().then(r=>setGroups(r.data.data)),activitiesApi.entitlements().then(r=>setGrants(r.data.data))]).catch(e=>setError(e.response?.data?.message||e.message))
 useEffect(()=>{if(!open)return;void refresh();const timer=setInterval(refresh,15000);return()=>clearInterval(timer)},[open])
 return <div className="border rounded-lg p-2 space-y-2 text-sm">
 <button type="button" className="text-primary font-bold" onClick={()=>setOpen(!open)}>{l('活动 / 拼团 / 兑奖','Activities / groups / rewards','Aktivitas / grup / hadiah')} {open?'▴':'▾'}</button>
 {quote?.applied&&<p className="text-green-700">{quote.applied.name} · −Rp {quote.discount.toLocaleString('id-ID')}</p>}
 {quote?.pendingSelections?.map((selection:any)=><label className="block" key={selection.activityId}>{selection.name}<select className="input" value={giftSelections[selection.activityId]||''} onChange={e=>onGiftChange({...giftSelections,[selection.activityId]:e.target.value})}><option value="">{l('选择赠品','Select reward','Pilih hadiah')}</option>{selection.rewards.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>)}
 {Object.entries(giftSelections).map(([id,value])=><button type="button" key={id} className="text-gray-500" onClick={()=>onGiftChange(Object.fromEntries(Object.entries(giftSelections).filter(([k])=>k!==id)))}>{l('重选赠品','Change reward','Ganti hadiah')} · {activities.find(a=>a.id===id)?.name||value}</button>)}
 {open&&<><p className="text-gray-500">{l('价格优惠择优不叠加；赠礼、积分和抽奖独立判断。','Best price only; gifts, points and draws qualify separately.','Harga terbaik saja; hadiah, poin dan undian dinilai terpisah.')}</p>{activities.filter(a=>activityState(a)==='active').map(a=><div key={a.id}>{a.name} · {activityLabel(a.type,i18n.language)}{a.type==='coupon'&&a.rule.couponTrigger==='claim'&&<button disabled={!memberId} className="ml-2 text-primary" onClick={()=>activitiesApi.claim(a.id,memberId!,crypto.randomUUID()).then(()=>refresh()).catch(e=>setError(e.response?.data?.message||e.message))}>{l('领券','Claim coupon','Klaim kupon')}</button>}{a.type==='group'&&<button disabled={!memberId} className="ml-2 text-primary" onClick={()=>activitiesApi.createGroup(a.id,[memberId!]).then(()=>refresh()).catch(e=>setError(e.response?.data?.message||e.message))}>{l('开团','Create group','Buat grup')}</button>}</div>)}
 <div className="flex gap-2"><input className="input" placeholder={l('邀请人推荐码','Inviter referral code','Kode referral teman')} value={inviterCode} onChange={e=>setInviterCode(e.target.value)}/><button disabled={!memberId||!inviterCode} className="text-primary" onClick={()=>activitiesApi.referral(memberId!,inviterCode).then(()=>{setInviterCode('');setError('')}).catch(e=>setError(e.response?.data?.message||e.message))}>{l('绑定邀请','Link inviter','Hubungkan')}</button></div>
 <select className="input" value={groupId} onChange={e=>onGroupChange(e.target.value)}><option value="">{l('不使用拼团','No group deal','Tanpa paket grup')}</option>{groups.filter(g=>g.status==='formed'&&g.memberIds.includes(memberId)).map(g=><option key={g.id} value={g.id}>{activities.find(a=>a.id===g.activityId)?.name} · {g.memberIds.length}</option>)}</select>
 {groups.filter(g=>g.status==='forming').map(g=><div key={g.id}>{activities.find(a=>a.id===g.activityId)?.name} · {g.memberIds.length}<button disabled={!memberId} className="text-primary ml-2" onClick={()=>activitiesApi.joinGroup(g.id,memberId!).then(()=>refresh()).catch(e=>setError(e.response?.data?.message||e.message))}>{l('当前会员参团','Join current member','Gabung member ini')}</button></div>)}
 <div className="max-h-48 overflow-auto">{grants.filter(g=>['ready','manual_review','pending'].includes(g.status)).map(g=><div className="border-t py-2" key={g.id}>{g.orderNumber} · {g.name} · {g.prize?.name||g.reward?.name||g.status}{g.status==='ready'&&<button className="ml-2 text-primary" onClick={()=>activitiesApi.fulfil(g.id).then(()=>refresh()).catch(e=>setError(e.response?.data?.message||e.message))}>{l('确认兑奖','Fulfil reward','Serahkan hadiah')}</button>}</div>)}</div>
 {error&&<p role="alert" className="text-red-700">{error}</p>}</>}
 </div>
}
