import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { activitiesApi } from '../../services/api'
import { Activity, ActivityType, ACTIVITY_TYPES } from '../../../../shared/utils/activities'
import { activityLabel, languageIndex } from '../../../../shared/utils/activityLabels'
const empty={name:'',description:'',theme:'',type:'special_price' as ActivityType,status:'draft' as Activity['status'],priority:0,timezone:'Asia/Jakarta',weekdays:[] as number[],channels:[] as string[],paymentMethods:[] as string[],productIds:[] as string[],specIds:[] as string[],memberOnly:false,memberLevels:[] as string[],showOnTv:true,rule:{price:0} as Activity['rule'],startsAt:'',endsAt:'',dailyStart:'',dailyEnd:'',imageUrl:''}
function wallTime(iso:string,zone:string){if(!iso)return '';const p=new Intl.DateTimeFormat('sv-SE',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));return p.replace(' ','T')}
function instant(wall:string,zone:string){if(!wall)return undefined;const naive=Date.parse(wall+'Z');const local=wallTime(new Date(naive).toISOString(),zone);const offset=Date.parse(local+'Z')-naive;return new Date(naive-offset).toISOString()}
export function ActivitiesPage(){
 const {i18n}=useTranslation(),lang=languageIndex(i18n.language),l=(zh:string,en:string,id:string)=>[zh,en,id][lang],client=useQueryClient()
 const [form,setForm]=useState<any>(null),[error,setError]=useState(''),[tab,setTab]=useState('activities'),[migration,setMigration]=useState<any>(null)
 const list=useQuery({queryKey:['unified-activities'],queryFn:()=>activitiesApi.list().then(r=>r.data.data),refetchInterval:15000})
 const resources=useQuery({queryKey:['activity-resources'],queryFn:()=>activitiesApi.resources().then(r=>r.data.data)})
 const grants=useQuery({queryKey:['activity-grants'],queryFn:()=>activitiesApi.entitlements().then(r=>r.data.data),enabled:tab==='grants',refetchInterval:15000})
 const terminals=useQuery({queryKey:['activity-terminals'],queryFn:()=>activitiesApi.terminals().then(r=>r.data.data),enabled:tab==='terminals',refetchInterval:15000})
 const onError=(e:any)=>setError(e.response?.data?.message||e.message)
 const save=useMutation({mutationFn:()=>{const {id,storeId,state,used,source,conflict,version,...data}=form;return activitiesApi.save({...data,startsAt:instant(data.startsAt,data.timezone),endsAt:instant(data.endsAt,data.timezone),dailyStart:data.dailyStart||undefined,dailyEnd:data.dailyEnd||undefined,...(id?{version}:{})},id)},onSuccess:()=>{setForm(null);setError('');client.invalidateQueries({queryKey:['unified-activities']})},onError})
 const set=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value})),rule=(key:string,value:any)=>setForm((f:any)=>({...f,rule:{...f.rule,[key]:value}}))
 const edit=(a:any)=>setForm({...a,startsAt:wallTime(a.startsAt,a.timezone),endsAt:wallTime(a.endsAt,a.timezone),dailyStart:a.dailyStart||'',dailyEnd:a.dailyEnd||''})
 const products=resources.data?.products||[],rewards=resources.data?.rewards||[],coupons=resources.data?.coupons||[]
 const numeric=(key:string,label:string,min=0,max=1000000000)=><label className="block">{label}<input className="input mt-1" type="number" min={min} max={max} value={form.rule[key]??''} onChange={e=>rule(key,e.target.value===''?undefined:Number(e.target.value))}/></label>
 const selections=(key:string,options:{id:string;name:string}[],inRule=false)=><div className="flex flex-wrap gap-3">{options.map(o=><label key={o.id} className="text-sm"><input type="checkbox" checked={(inRule?form.rule[key]:form[key]||[])?.includes(o.id)||false} onChange={e=>{const old=(inRule?form.rule[key]:form[key])||[];const value=e.target.checked?[...old,o.id]:old.filter((x:string)=>x!==o.id);inRule?rule(key,value):set(key,value)}}/> {o.name}</label>)}</div>
 const status=(value:string)=>({draft:l('草稿','Draft','Draf'),scheduled:l('待开始','Scheduled','Terjadwal'),active:l('进行中','Active','Aktif'),paused:l('暂停','Paused','Dijeda'),ended:l('已结束','Ended','Selesai'),review:l('待确认','Review','Perlu tinjauan'),published:l('发布','Publish','Terbitkan')}[value]||value)
 return <div className="space-y-5 p-4">
 <div className="flex justify-between items-center"><div><h1 className="text-2xl font-bold">{l('统一活动管理','Activities','Aktivitas')}</h1><p className="text-gray-500">{l('一次配置，收银自动执行，电视自动播放。价格优惠择优不叠加。','Configure once. POS applies the best price; TV plays active offers.','Atur sekali. POS memilih harga terbaik; TV menampilkan promo aktif.')}</p></div><button className="btn-primary" onClick={()=>{setForm({...empty,rule:{price:0}});setError('')}}>{l('创建活动','Create activity','Buat aktivitas')}</button></div>
 <div className="flex gap-3">{['activities','grants','terminals','migration'].map(t=><button key={t} className={tab===t?'btn-primary':'btn-ghost'} onClick={()=>setTab(t)}>{({activities:l('活动','Activities','Aktivitas'),grants:l('权益与兑奖','Rewards','Hadiah'),terminals:l('终端同步','Terminals','Terminal'),migration:l('旧数据迁移','Migration','Migrasi')} as any)[t]}</button>)}<Link className="btn-ghost" to="/settings/tv-screen">{l('电视设置','TV settings','Pengaturan TV')}</Link></div>
 {error&&<div role="alert" className="p-3 bg-red-50 text-red-700 whitespace-pre-wrap">{error}</div>}
 {resources.isError&&form&&<div role="alert">{l('商品、赠品或券模板加载失败，请重试。','Could not load products, rewards or coupons. Please retry.','Gagal memuat produk, hadiah, atau kupon. Coba lagi.')}</div>}
 {list.isError&&<div role="alert">{l('活动加载失败，请重试','Failed to load activities. Please retry.','Gagal memuat aktivitas. Coba lagi.')}</div>}
 {tab==='activities'&&!form&&<div className="space-y-3">{list.isLoading?<p>…</p>:(list.data||[]).map((a:any)=><div className="card flex justify-between gap-4" key={a.id}><div><div className="font-bold">{a.name} <span className="text-sm font-normal">{status(a.state)}</span></div><p>{activityLabel(a.type,i18n.language)} · {a.description}</p><p className="text-xs text-gray-500">{a.startsAt?new Date(a.startsAt).toLocaleString():l('立即开始','Immediate','Segera')} — {a.endsAt?new Date(a.endsAt).toLocaleString():l('长期有效','No end date','Tanpa akhir')} · {a.timezone} · {a.used}/{a.limit??'∞'}</p>{a.conflict&&<p className="text-amber-700">{a.conflict}</p>}</div><button className="btn-ghost" onClick={()=>edit(a)}>{l('编辑','Edit','Edit')}</button></div>)}{!list.isLoading&&!list.data?.length&&<div className="card">{l('暂无活动，请创建活动。','No activities yet. Create an activity.','Belum ada aktivitas. Buat aktivitas baru.')}</div>}</div>}
 {form&&<form className="card space-y-6" onSubmit={e=>{e.preventDefault();save.mutate()}}>
 <div className="grid md:grid-cols-3 gap-4"><label>{l('活动名称','Name','Nama')}<input required className="input" value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>{l('活动类型','Type','Jenis')}<select className="input" value={form.type} onChange={e=>{set('type',e.target.value);set('rule',{})}}>{ACTIVITY_TYPES.map(t=><option key={t} value={t}>{activityLabel(t,i18n.language)}</option>)}</select></label><label>{l('状态','Status','Status')}<select className="input" value={form.status} onChange={e=>set('status',e.target.value)}>{['draft','published','paused','ended'].map(s=><option key={s} value={s}>{status(s)}</option>)}</select></label><label>{l('主题','Theme','Tema')}<input className="input" value={form.theme||''} onChange={e=>set('theme',e.target.value)}/></label><label>{l('宣传说明','Description','Deskripsi')}<textarea className="input" value={form.description} onChange={e=>set('description',e.target.value)}/></label><label>{l('宣传图片地址','Image URL','URL gambar')}<input className="input" value={form.imageUrl||''} onChange={e=>set('imageUrl',e.target.value)}/></label></div>
 <fieldset className="space-y-3"><legend className="font-bold">{l('活动时间与参与条件','Schedule and eligibility','Jadwal dan persyaratan')}</legend><div className="grid md:grid-cols-3 gap-4"><label>{l('开始日期时间','Starts at','Mulai')}<input type="datetime-local" className="input" value={form.startsAt} onChange={e=>set('startsAt',e.target.value)}/></label><label>{l('结束日期时间','Ends at','Berakhir')}<input type="datetime-local" className="input" value={form.endsAt} onChange={e=>set('endsAt',e.target.value)}/></label><label>{l('门店时区','Store time zone','Zona waktu toko')}<input className="input" required value={form.timezone} onChange={e=>set('timezone',e.target.value)}/></label><label>{l('每日开始时刻','Daily start','Jam mulai')}<input type="time" className="input" value={form.dailyStart} onChange={e=>set('dailyStart',e.target.value)}/></label><label>{l('每日结束时刻（可跨午夜）','Daily end (overnight allowed)','Jam akhir (boleh lintas malam)')}<input type="time" className="input" value={form.dailyEnd} onChange={e=>set('dailyEnd',e.target.value)}/></label><label>{l('活动限额（留空不限）','Usage limit (blank = unlimited)','Batas penggunaan (kosong = tanpa batas)')}<input type="number" min="1" className="input" value={form.limit??''} onChange={e=>set('limit',e.target.value?Number(e.target.value):undefined)}/></label><label>{l('优先级（同价时使用）','Tie-break priority','Prioritas jika harga sama')}<input className="input" type="number" min="0" max="1000" value={form.priority} onChange={e=>set('priority',Number(e.target.value))}/></label></div>
 <p>{l('重复星期（不选表示每天）','Weekdays (none = every day)','Hari (kosong = setiap hari)')}</p><div className="flex gap-3">{[0,1,2,3,4,5,6].map(day=><label key={day}><input type="checkbox" checked={form.weekdays.includes(day)} onChange={e=>set('weekdays',e.target.checked?[...form.weekdays,day]:form.weekdays.filter((d:number)=>d!==day))}/> {new Intl.DateTimeFormat(i18n.language,{weekday:'short'}).format(new Date(2026,9,4+day))}</label>)}</div>
 <p>{l('适用商品（不选表示全部）','Products (none = all)','Produk (kosong = semua)')}</p>{selections('productIds',products)}
 <p>{l('适用规格（不选表示全部）','Specifications (none = all)','Ukuran (kosong = semua)')}</p>{selections('specIds',products.flatMap((p:any)=>p.specs.map((s:any)=>({id:s.id,name:p.name+' / '+s.name}))))}
 <p>{l('适用渠道','Channels','Kanal')}</p>{selections('channels',['DINE_IN','TAKEAWAY','GOFOOD','GRAB','SHOPEE','POS'].map(id=>({id,name:id})))}
 <p>{l('适用支付方式','Payment methods','Metode pembayaran')}</p>{selections('paymentMethods',['cash','qris','gopay','ovo','dana','shopeepay','debit','card','member'].map(id=>({id,name:id})))}
 <label><input type="checkbox" checked={form.memberOnly} onChange={e=>set('memberOnly',e.target.checked)}/> {l('仅会员参与','Members only','Khusus member')}</label>{selections('memberLevels',['bronze','silver','gold','diamond'].map(id=>({id,name:id})))}
 </fieldset>
 <fieldset className="space-y-4"><legend className="font-bold">{l('活动规则','Rules','Aturan')}</legend><div className="grid md:grid-cols-3 gap-4">
 {numeric('minAmount',l('最低金额 Rp（价格优惠按原价，赠礼按实付）','Minimum Rp (price: base; rewards: paid)','Minimum Rp (diskon: dasar; hadiah: dibayar)'))}
 {['special_price','member_price','bundle','addon','group','birthday','welcome'].includes(form.type)&&numeric('price',l('活动价 Rp','Offer price Rp','Harga promo Rp'))}
 {['percent','nth_cup','birthday','welcome','group'].includes(form.type)&&numeric('percent',l('减免百分比（50 表示减半）','Discount % (50 = half off)','Diskon % (50 = separuh)'),0,100)}
 {['fixed','upgrade','birthday','welcome'].includes(form.type)&&numeric('amount',l('减免金额 Rp','Discount Rp','Potongan Rp'))}
 {numeric('maxDiscount',l('减免上限 Rp（留空不限）','Maximum discount Rp (optional)','Maksimum diskon Rp (opsional)'))}
 {form.type==='nth_cup'&&numeric('nth',l('每组杯数 / 第几杯优惠','Group size / discounted cup','Ukuran grup / cup diskon'),2,100)}
 {form.type==='buy_get'&&<>{numeric('buy',l('购买杯数','Buy quantity','Jumlah beli'),1,100)}{numeric('get',l('赠送杯数','Free quantity','Jumlah gratis'),1,100)}</>}
 {form.type==='points'&&<>{numeric('multiplier',l('积分倍率','Points multiplier','Pengali poin'),1,100)}{numeric('points',l('额外积分','Bonus points','Bonus poin'))}</>}
 {form.type==='stamps'&&numeric('stampsRequired',l('集满杯数','Stamps required','Target stempel'),1,1000)}
 {form.type==='group'&&numeric('participants',l('成团会员人数','Members required','Jumlah member'),2,100)}
 {form.type==='referral'&&<>{numeric('inviterPoints',l('邀请人奖励积分','Inviter points','Poin pengundang'))}{numeric('inviteePoints',l('被邀请人奖励积分','Invitee points','Poin teman'))}</>}
 {numeric('perMemberLimit',l('每位会员参与次数（留空不限）','Per-member limit (optional)','Batas per member (opsional)'),1,10000)}
 </div>
 {['gift','stamps','birthday','welcome'].includes(form.type)&&<><p>{l('可选赠品（多个时收银选择）','Rewards (cashier selects when multiple)','Hadiah (kasir memilih jika lebih dari satu)')}</p>{selections('rewardIds',rewards,true)}</>}
 {form.type==='coupon'&&<label>{l('发券方式','Coupon trigger','Cara pemberian kupon')}<select className="input" value={form.rule.couponTrigger||'paid'} onChange={e=>rule('couponTrigger',e.target.value)}><option value="paid">{l('支付后自动送券','After payment','Setelah pembayaran')}</option><option value="claim">{l('会员在门店领券','Claim in store','Klaim di toko')}</option></select></label>}
 {form.type==='addon'&&selections('addonNames',products.flatMap((p:any)=>p.addons.map((a:any)=>({id:a.addon.name,name:a.addon.name}))).filter((v:any,n:number,all:any[])=>all.findIndex(x=>x.id===v.id)===n),true)}
 {['coupon','birthday','welcome','referral'].includes(form.type)&&<label>{l('赠送优惠券模板','Coupon template','Template kupon')}<select className="input" value={form.rule.couponId||''} onChange={e=>rule('couponId',e.target.value||undefined)}><option value="">—</option>{coupons.map((c:any)=><option key={c.id} value={c.id}>{c.code}</option>)}</select></label>}
 {form.type==='bundle'&&<div className="space-y-2">{(form.rule.components||[]).map((c:any,n:number)=><div className="flex gap-2" key={n}><select required className="input" value={c.productId} onChange={e=>rule('components',form.rule.components.map((x:any,k:number)=>k===n?{...x,productId:e.target.value,specId:undefined}:x))}><option value="">{l('商品','Product','Produk')}</option>{products.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="input" value={c.specId||''} onChange={e=>rule('components',form.rule.components.map((x:any,k:number)=>k===n?{...x,specId:e.target.value||undefined}:x))}><option value="">{l('任意规格','Any size','Semua ukuran')}</option>{products.find((p:any)=>p.id===c.productId)?.specs.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input w-24" type="number" min="1" max="100" value={c.quantity} onChange={e=>rule('components',form.rule.components.map((x:any,k:number)=>k===n?{...x,quantity:Number(e.target.value)}:x))}/><button type="button" onClick={()=>rule('components',form.rule.components.filter((_:any,k:number)=>k!==n))}>×</button></div>)}<button type="button" className="btn-ghost" onClick={()=>rule('components',[...(form.rule.components||[]),{productId:'',quantity:1}])}>{l('添加套餐商品','Add bundle item','Tambah produk paket')}</button></div>}
 {form.type==='tiered'&&<div>{(form.rule.tiers||[]).map((tier:any,n:number)=><div className="flex gap-2 my-2" key={n}>{['minAmount','amount'].map(key=><label key={key}>{key==='minAmount'?l('满额 Rp','Spend Rp','Belanja Rp'):l('减免 Rp','Save Rp','Potongan Rp')}<input type="number" min="0" className="input" value={tier[key]} onChange={e=>rule('tiers',form.rule.tiers.map((x:any,k:number)=>k===n?{...x,[key]:Number(e.target.value)}:x))}/></label>)}<button type="button" onClick={()=>rule('tiers',form.rule.tiers.filter((_:any,k:number)=>k!==n))}>×</button></div>)}<button type="button" className="btn-ghost" onClick={()=>rule('tiers',[...(form.rule.tiers||[]),{minAmount:0,amount:0}])}>{l('添加阶梯','Add tier','Tambah tingkat')}</button></div>}
 {form.type==='lottery'&&<div className="space-y-3"><p>{l('支付后自动开奖，奖品库存为零后停止抽取。','Automatically drawn after payment. Empty prizes are excluded.','Diundi otomatis setelah pembayaran. Hadiah habis tidak dipilih.')}</p>{(form.rule.prizes||[]).map((p:any,n:number)=>{const change=(key:string,value:any)=>rule('prizes',form.rule.prizes.map((x:any,k:number)=>k===n?{...x,[key]:value}:x));return <div className="border rounded p-3 grid md:grid-cols-3 gap-2" key={p.id}><label>{l('奖品名称','Prize name','Nama hadiah')}<input required className="input" value={p.name} onChange={e=>change('name',e.target.value)}/></label><label>{l('权重','Weight','Bobot')}<input type="number" min="0" className="input" value={p.weight} onChange={e=>change('weight',Number(e.target.value))}/></label><label>{l('剩余份数（留空不限）','Remaining (blank = unlimited)','Sisa (kosong = tanpa batas)')}<input type="number" min="0" className="input" value={p.remaining??''} onChange={e=>change('remaining',e.target.value?Number(e.target.value):undefined)}/></label><label>{l('颜色','Color','Warna')}<input type="color" value={p.color} onChange={e=>change('color',e.target.value)}/></label><label>{l('关联赠品','Linked reward','Hadiah terkait')}<select className="input" value={p.rewardId||''} onChange={e=>change('rewardId',e.target.value||undefined)}><option value="">—</option>{rewards.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>{l('关联优惠券','Linked coupon','Kupon terkait')}<select className="input" value={p.couponId||''} onChange={e=>change('couponId',e.target.value||undefined)}><option value="">—</option>{coupons.map((c:any)=><option key={c.id} value={c.id}>{c.code}</option>)}</select></label><button type="button" className="btn-ghost" onClick={()=>rule('prizes',form.rule.prizes.filter((_:any,k:number)=>k!==n))}>{l('删除奖品','Remove prize','Hapus hadiah')}</button></div>})}<button type="button" className="btn-ghost" onClick={()=>rule('prizes',[...(form.rule.prizes||[]),{id:crypto.randomUUID(),name:'',code:'',color:'#ef4444',weight:1}])}>{l('添加奖品','Add prize','Tambah hadiah')}</button></div>}
 <label><input type="checkbox" checked={form.showOnTv} onChange={e=>set('showOnTv',e.target.checked)}/> {l('电视自动播放此活动','Show activity on TV','Tampilkan aktivitas di TV')}</label>
 </fieldset><div className="flex gap-3"><button className="btn-primary" disabled={save.isPending}>{l('保存活动','Save activity','Simpan aktivitas')}</button><button type="button" className="btn-ghost" onClick={()=>setForm(null)}>{l('取消','Cancel','Batal')}</button></div></form>}
 {tab==='grants'&&<div className="space-y-2">{(grants.data||[]).map((g:any)=><div className="card flex justify-between" key={g.id}><div>{g.orderNumber} · {g.name} · {g.prize?.name||g.reward?.name||g.coupon?.code||g.pointsAwarded||''}<p>{g.status}{g.reason?' · '+g.reason:''}</p></div>{g.status==='ready'&&<button className="btn-primary" onClick={()=>activitiesApi.fulfil(g.id).then(()=>client.invalidateQueries({queryKey:['activity-grants']})).catch(onError)}>{l('确认兑现','Fulfil','Serahkan')}</button>}</div>)}</div>}
 {tab==='terminals'&&<div className="space-y-2">{(terminals.data||[]).map((t:any)=><div className="card" key={t.id}>{t.kind==='pos'?'POS':'TV'} · {t.id} · {t.online?l('在线','Online','Online'):l('离线','Offline','Offline')} · {l('同步版本','Version','Versi')} {t.version} · {new Date(t.lastSeen).toLocaleString()}</div>)}</div>}
 {tab==='migration'&&<div className="card space-y-4"><p>{l('迁移按来源去重。重复或无效旧规则进入草稿待确认，不自动启用。','Migration deduplicates sources. Conflicting or invalid rules remain drafts for review.','Migrasi mencegah duplikasi sumber. Aturan konflik menjadi draf untuk ditinjau.')}</p><button className="btn-ghost" onClick={()=>activitiesApi.migration().then(r=>setMigration(r.data.data)).catch(onError)}>{l('预览迁移','Preview migration','Pratinjau migrasi')}</button>{migration&&<><p>{l('新增 / 跳过 / 冲突','Create / skip / conflicts','Buat / lewati / konflik')}: {migration.created} / {migration.skipped} / {migration.conflicts}</p>{migration.activities.map((a:any)=><p key={a.id}>{a.name} {a.conflict||''}</p>)}<button className="btn-primary" onClick={()=>activitiesApi.migration(true).then(r=>{setMigration(r.data.data);client.invalidateQueries({queryKey:['unified-activities']})}).catch(onError)}>{l('应用迁移','Apply migration','Terapkan migrasi')}</button></>}</div>}
 </div>
}
