import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Loader2 } from 'lucide-react'
import { messageApi } from '../../services/api'
import { MarketingError, useMarketingCopy } from '../../components/marketing/MarketingLayout'

export function MessageLogPage() {
  const l=useMarketingCopy(),[status,setStatus]=useState(''),[offset,setOffset]=useState(0)
  const statusLabels:Record<string,string>={pending:l('待发送','Pending','Menunggu'),sent:l('已发送','Sent','Dikirim'),delivered:l('已送达','Delivered','Diterima'),failed:l('失败','Failed','Gagal')}
  const logs=useQuery({queryKey:['marketing-message-logs',status,offset],queryFn:()=>messageApi.logs({status:status||undefined,limit:50,offset}).then(response=>response.data.data)})
  return <div className="space-y-4"><div className="marketing-toolbar"><select className="input sm:w-44" aria-label={l('发送状态','Delivery status','Status pengiriman')} value={status} onChange={event=>{setStatus(event.target.value);setOffset(0)}}><option value="">{l('全部状态','All statuses','Semua status')}</option>{['pending','sent','delivered','failed'].map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select><p className="text-sm text-gray-500">{logs.data?.total||0} {l('条记录','records','catatan')}</p></div>{logs.isError?<MarketingError retry={()=>logs.refetch()}/>:logs.isLoading?<div className="card flex justify-center py-10"><Loader2 className="animate-spin text-primary"/></div>:<div className="card !p-0 overflow-x-auto"><table className="min-w-[650px]"><thead><tr>{[l('接收会员','Member','Member'),l('渠道','Channel','Kanal'),l('内容','Content','Konten'),l('状态','Status','Status'),l('时间','Time','Waktu')].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{(logs.data?.list||[]).map((row:any)=><tr key={row.id} className="border-t border-border"><td>{row.member?.name||'—'}</td><td>{row.channel?.name||row.channelType}</td><td className="max-w-sm break-words">{row.body||row.content}{row.errorMessage&&<p className="text-xs text-red-600 mt-1">{row.errorMessage}</p>}</td><td><span className={'badge '+(row.status==='failed'?'badge-error':['sent','delivered'].includes(row.status)?'badge-success':'badge-gray')}>{statusLabels[row.status]||row.status}</span></td><td>{new Date(row.createdAt).toLocaleString(undefined,{timeZone:'Asia/Jakarta'})}</td></tr>)}</tbody></table>{!logs.data?.list?.length&&<p className="p-10 text-center text-sm text-gray-500">{l('暂无发送记录','No delivery records','Belum ada catatan pengiriman')}</p>}</div>}<div className="flex gap-3"><button className="btn-secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>{l('上一页','Previous','Sebelumnya')}</button><button className="btn-secondary" disabled={offset+50>=(logs.data?.total||0)} onClick={()=>setOffset(offset+50)}>{l('下一页','Next','Berikutnya')}</button></div></div>
}
