import { useAuthStore } from '../../stores/auth'
import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { marketingApi } from '../../services/api'
import { DEFAULT_TV_CONFIG, normalizeTvConfig } from '../../../../shared/utils/tvScreenConfig'
import { languageIndex } from '../../../../shared/utils/activityLabels'
export function TvScreenConfigPage(){
 const {i18n}=useTranslation(),language=languageIndex(i18n.language),l=(zh:string,en:string,id:string)=>[zh,en,id][language]
 const [cfg,setCfg]=useState<any>(DEFAULT_TV_CONFIG),[token,setToken]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false)
 useEffect(()=>{marketingApi.getTvScreenConfig().then(r=>{setCfg(normalizeTvConfig(r.data.data));setToken(r.data.data.displayToken||'')}).catch(e=>setError(e.response?.data?.message||e.message))},[])
 const set=(key:string,value:any)=>setCfg((c:any)=>({...c,[key]:value}))
 const save=async()=>{setSaving(true);setError('');setSaved(false);try{await marketingApi.saveTvScreenConfig({enabled:cfg.enabled,storeName:cfg.storeName,welcomeText:cfg.welcomeText,carouselIntervalSeconds:Number(cfg.carouselIntervalSeconds),layout:cfg.layout,mediaFiles:cfg.mediaFiles,ticker:cfg.ticker,soundEnabled:cfg.soundEnabled??true});setSaved(true)}catch(e:any){setError(e.response?.data?.message||e.message)}finally{setSaving(false)}}
 // Use the already configured POS origin; display tokens contain no cashier permissions.
 const posOrigin=(window.location.hostname==='admin.aicube.online'?'https://pos.aicube.online':window.location.origin.replace(/:\d+$/,':6063'))
 const storeId=useAuthStore(state=>state.user?.storeId)||''
 const displayLink=`${posOrigin}/#/tv-display?storeId=${encodeURIComponent(storeId)}&displayToken=${encodeURIComponent(token)}`
 return <div className="space-y-5"><h2 className="text-xl font-bold">{l('电视大屏终端','TV terminal','Terminal TV')}</h2><div className="p-4 bg-blue-50 rounded"><p>{l('活动价格、奖品和参与条件统一在营销活动中管理，电视自动拉取并播放。','Prices, prizes and eligibility are managed in Activities. TV automatically plays active content.','Harga, hadiah dan syarat diatur di Aktivitas. TV menampilkan konten aktif otomatis.')}</p><Link className="text-primary underline" to="/marketing/promotions/activities">{l('前往活动管理','Open Activities','Buka Aktivitas')}</Link></div>
 {error&&<p role="alert" className="text-red-600">{error}</p>}{saved&&<p role="status" className="text-green-600">{l('已保存','Saved','Tersimpan')}</p>}
 <label className="block"><input type="checkbox" checked={cfg.enabled} onChange={e=>set('enabled',e.target.checked)}/> {l('启用电视播放','Enable display','Aktifkan layar')}</label>
 <div className="grid md:grid-cols-2 gap-4"><label>{l('门店显示名称','Display name','Nama toko')}<input className="input" value={cfg.storeName} onChange={e=>set('storeName',e.target.value)}/></label><label>{l('欢迎语','Welcome message','Pesan sambutan')}<input className="input" value={cfg.welcomeText} onChange={e=>set('welcomeText',e.target.value)}/></label><label>{l('轮播间隔（秒）','Carousel seconds','Interval detik')}<input className="input" type="number" min="2" max="300" value={cfg.carouselIntervalSeconds} onChange={e=>set('carouselIntervalSeconds',Number(e.target.value))}/></label><label>{l('媒体区域宽度 %','Media width %','Lebar media %')}<input className="input" type="number" min="10" max="90" value={cfg.layout.columns[0].width} onChange={e=>set('layout',{columns:[{width:Number(e.target.value),content:'media'},{width:100-Number(e.target.value),content:'specials'}]})}/></label></div>
 <label className="block"><input type="checkbox" checked={cfg.soundEnabled??true} onChange={e=>set('soundEnabled',e.target.checked)}/> {l('默认开启声音','Enable sound by default','Aktifkan suara')}</label>
 <h3 className="font-bold">{l('媒体轮播','Media carousel','Media bergilir')}</h3>{cfg.mediaFiles.map((m:any,n:number)=><div className="flex gap-3" key={n}><input className="input" aria-label={l('媒体地址','Media URL','URL media')} placeholder="https://… /uploads/…" value={m.url} onChange={e=>set('mediaFiles',cfg.mediaFiles.map((x:any,i:number)=>i===n?{...x,url:e.target.value}:x))}/><input className="input" aria-label={l('标题','Title','Judul')} value={m.title||''} onChange={e=>set('mediaFiles',cfg.mediaFiles.map((x:any,i:number)=>i===n?{...x,title:e.target.value}:x))}/><button className="btn-ghost" onClick={()=>set('mediaFiles',cfg.mediaFiles.filter((_:any,i:number)=>i!==n))}>×</button></div>)}<button className="btn-ghost" onClick={()=>set('mediaFiles',[...cfg.mediaFiles,{url:'',title:''}])}>{l('添加媒体','Add media','Tambah media')}</button>
 <label className="block"><input type="checkbox" checked={cfg.ticker.enabled} onChange={e=>set('ticker',{...cfg.ticker,enabled:e.target.checked})}/> {l('启用跑马灯','Enable ticker','Aktifkan teks berjalan')}</label><input className="input" aria-label={l('跑马灯文字','Ticker text','Teks berjalan')} value={cfg.ticker.text} onChange={e=>set('ticker',{...cfg.ticker,text:e.target.value})}/>
 <p className="text-sm text-gray-500">{l('首次打开授权链接后，电视会记住门店。将播放页收藏或设为主页，以后无需输入完整网址。','Open the authorized link once. TV remembers the store. Bookmark the display or set it as your homepage.','Buka tautan otorisasi sekali. TV mengingat toko. Simpan sebagai bookmark atau beranda.')}</p>
 <div className="flex gap-4"><button className="btn-primary" disabled={saving} onClick={save}>{l('保存电视设置','Save TV settings','Simpan pengaturan TV')}</button>{token&&storeId&&<button className="btn-ghost" onClick={()=>navigator.clipboard.writeText(displayLink).then(()=>setSaved(true)).catch(()=>setError(l('复制失败，请使用打开链接按钮。','Copy failed. Use the open link button.','Salin gagal. Gunakan tombol buka tautan.')))}>{l('复制播放链接','Copy display link','Salin tautan layar')}</button>}{token&&storeId&&<a className="btn-ghost" href={displayLink} target="_blank" rel="noreferrer">{l('打开电视播放链接','Open display link','Buka tautan layar')}</a>}</div>
 </div>
}
